// import { Geist, Geist_Mono,Oswald, Inter } from "next/font/google";
// import "./globals.css";
// import NavBar from "@/components/NavBar";
// import Footer from "@/components/Footer";
// import { ContextApi } from "@/components/share/ContextApi";
// import { PlanProvider } from '@/components/share/PlanContext'
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const oswald = Oswald({
//   subsets: ["latin"],
//   variable: "--font-oswald",
// });

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${inter.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <ContextApi>
//   <PlanProvider>
//     <NavBar/>
//     {children}
//   </PlanProvider>
// </ContextApi>
//         </body>
        
//     </html>
//   );
// }



import { PlanProvider } from '@/components/share/PlanContext'
import { ContextApi } from '@/components/share/ContextApi'
import { Toaster } from 'react-hot-toast'
import NavBar from '@/components/NavBar'
import './globals.css'
import Footer from '@/components/Footer'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextApi>
          <PlanProvider>
            <NavBar />
            {children}
            <Toaster position="top-right" />
            <Footer/>
          </PlanProvider>
        </ContextApi>
      </body>
    </html>
  )
}